# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: Update Python dep"
      prefix-development: "chore: Update Python dev dep"
  - package-ecosystem: "github-actions" # See documentation for possible values
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`
    # You can use `directory: "/"`
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: Update GHA dep"
      prefix-development: "chore: Update GHA dev dep"
