version: '3.8'

services:

  web:
    build:
      context: ./.
      dockerfile: Dockerfile
    command: alembic init -t async swiftpack/migrations  
    # command:  uvicorn --port 8000 swiftpack.src.main:create_app --factory --workers 1 --host 0.0.0.0
    # command: echo $PATH
    # command: uvicorn swiftpack.src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    # volumes:
    #   - ./swiftpack:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/swiftpack
    depends_on:
      - db

  db:
    image: postgres:15.7-alpine3.20
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=swiftpack
